apiVersion: apps/v1
kind: Deployment
metadata:
  name: eco-miner-deployment
  labels:
    app: eco-miner
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eco-miner
  template:
    metadata:
      labels:
        app: eco-miner
    spec:
      containers:
      - name: eco-miner
          image: alpine
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
        restartPolicy: OnFailure